import { Maison } from '@/types';

export const DEMO_MAISONS: Maison[] = [
  {
    id: '1',
    titre: 'Villa Moderne avec Piscine - Douala',
    description: 'Superbe villa moderne avec piscine, 4 chambres, salle de cinéma, garage pour 2 voitures. Idéale pour famille.',
    prix: 45000000,
    type: 'vente',
    ville: 'Douala',
    quartier: 'Bonanjo',
    chambres: 4,
    sallesBain: 3,
    superficie: 250,
    statut: 'disponible',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    photos: [
      {
        id: 'photo1-1',
        url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
        publicId: 'immo/villa1',
        isMain: true,
        maisonId: '1',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'photo1-2',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
        publicId: 'immo/villa1-2',
        isMain: false,
        maisonId: '1',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'photo1-3',
        url: 'https://images.unsplash.com/photo-1570129477492-45a003537e1c?w=800&q=80',
        publicId: 'immo/villa1-3',
        isMain: false,
        maisonId: '1',
        createdAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    titre: 'Appartement de Luxe - Yaoundé Centre',
    description: 'Penthouse 3 chambres, vue panoramique sur la ville, ascenseur privé, gardien 24h/24.',
    prix: 28000000,
    type: 'vente',
    ville: 'Yaoundé',
    quartier: 'Centre',
    chambres: 3,
    sallesBain: 2,
    superficie: 180,
    statut: 'disponible',
    videoUrl: null,
    photos: [
      {
        id: 'photo2-1',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        publicId: 'immo/apt1',
        isMain: true,
        maisonId: '2',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'photo2-2',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        publicId: 'immo/apt1-2',
        isMain: false,
        maisonId: '2',
        createdAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    titre: 'Maison Familiale - Douala, Bonakuma',
    description: 'Maison spacieuse avec jardin, 3 chambres, cuisine neuve, parking sécurisé.',
    prix: 22000000,
    type: 'vente',
    ville: 'Douala',
    quartier: 'Bonakuma',
    chambres: 3,
    sallesBain: 2,
    superficie: 200,
    statut: 'disponible',
    videoUrl: null,
    photos: [
      {
        id: 'photo3-1',
        url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
        publicId: 'immo/maison1',
        isMain: true,
        maisonId: '3',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'photo3-2',
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
        publicId: 'immo/maison1-2',
        isMain: false,
        maisonId: '3',
        createdAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    titre: 'Studio Meublé - Douala, Akwa',
    description: 'Studio moderne tout équipé, idéal pour jeune professionnel, proche commercial.',
    prix: 3500000,
    type: 'location',
    ville: 'Douala',
    quartier: 'Akwa',
    chambres: 1,
    sallesBain: 1,
    superficie: 45,
    statut: 'loue',
    videoUrl: null,
    photos: [
      {
        id: 'photo4-1',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
        publicId: 'immo/studio1',
        isMain: true,
        maisonId: '4',
        createdAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    titre: 'Terrain Constructible - Yaoundé Plateau',
    description: 'Beau terrain 500m², bien situé, documents complets, prêt pour construction.',
    prix: 15000000,
    type: 'vente',
    ville: 'Yaoundé',
    quartier: 'Plateau',
    chambres: 0,
    sallesBain: 0,
    superficie: 500,
    statut: 'vendu',
    videoUrl: null,
    photos: [
      {
        id: 'photo5-1',
        url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80',
        publicId: 'immo/terrain1',
        isMain: true,
        maisonId: '5',
        createdAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    titre: 'Duplex Moderne - Douala, Deido',
    description: 'Duplex neuf 5 chambres, double garage, ascenseur, climatisation centrale, finitions haut de gamme.',
    prix: 55000000,
    type: 'vente',
    ville: 'Douala',
    quartier: 'Deido',
    chambres: 5,
    sallesBain: 4,
    superficie: 350,
    statut: 'disponible',
    videoUrl: 'https://www.youtube.com/embed/9bZkp7q19f0',
    photos: [
      {
        id: 'photo6-1',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
        publicId: 'immo/duplex1',
        isMain: true,
        maisonId: '6',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'photo6-2',
        url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
        publicId: 'immo/duplex1-2',
        isMain: false,
        maisonId: '6',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'photo6-3',
        url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7d8a28?w=800&q=80',
        publicId: 'immo/duplex1-3',
        isMain: false,
        maisonId: '6',
        createdAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

